java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\1"

java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\2"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\3"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\4"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\5"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\6"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\7"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\8"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\9"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\10"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\11"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\12"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\13"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\14"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\15"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\16"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\17"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\18"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\19"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\20"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\21"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\22"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\23"




java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\25"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\26"

java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\27"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\28"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\29"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\30"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\31"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\32"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\33"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\34"


java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\35"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\36"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\37"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\38"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\40"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\41"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\42"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\43"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\44"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\46"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\47"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\48"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\49"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\50"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\51"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\52"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\53"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\54"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\55"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\56"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\57"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\58"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\60"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\61"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\62"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\65"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\66"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\67"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\68"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\70"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\71"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\72"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\73"

java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\74"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\75"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\76"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\77"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\78"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\79"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\81"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\82"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\83"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\84"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\85"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\86"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\87"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\88"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\89"
java   -jar codeSourceRefactor-1.0-SNAPSHOT-all.jar "D:\test\done\91"
